/**
 * Generate docs/openapi.yaml from the route schemas. No services are contacted: the
 * database pool and S3 client connect lazily and are never used.
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { stringify } from 'yaml';
import { loadEnv } from '@okf/config';
import { createDb } from '@okf/db';
import type { QueryEngine } from '@okf/query';
import { createStorage } from '@okf/storage';
import { buildApp } from '../src/app';
import { MemoryMailer } from '../src/lib/mailer';
import { createMetrics } from '../src/lib/observability';
import { PostgresSearchProvider } from '../src/services/search';

const env = loadEnv({
  DATABASE_URL: 'postgres://unused@localhost/unused',
  REDIS_URL: 'redis://localhost:6379',
  S3_BUCKET: 'unused',
  S3_ACCESS_KEY_ID: 'unused',
  S3_SECRET_ACCESS_KEY: 'unused',
  LOG_LEVEL: 'silent',
  ...Object.fromEntries(Object.entries(process.env).filter(([k]) => k.startsWith('RATE_LIMIT') || k === 'AUTH_RATE_LIMIT_MAX')),
});
const db = createDb(env.DATABASE_URL, 1);
const unusedQuery: QueryEngine = {
  structured: () => Promise.reject(new Error('unused')),
  sql: () => Promise.reject(new Error('unused')),
  close: async () => undefined,
};
const app = await buildApp({
  env,
  db: db.db,
  storage: createStorage(env),
  redis: null,
  query: unusedQuery,
  mailer: new MemoryMailer(),
  metrics: createMetrics(),
  reporter: { capture: () => undefined },
  search: new PostgresSearchProvider(db.db),
});
await app.ready();
const out = path.resolve(import.meta.dirname, '../../../docs/openapi.yaml');
await writeFile(out, `# Generated by \`npm run openapi\` from the API route schemas. Do not edit by hand.\n${stringify(app.swagger(), { lineWidth: 0 })}`);
await app.close();
await db.close();
console.log(`wrote ${out}`);
